### ISSUE TITLE
<fstream> still needed

### ISSUE THREAD

**Issue by kuangdai** [shaovoon/simplebinstream#8]
After updating to 1.0.4, my project fails to compile.  I am using clang on OSX. I guess <fstream> is still needed for cross-platform.

**Comment by kuangdai** [comment]
Error message without <fstream>:

Incomplete type 'std::__1::ios_base' named in nested name specifier

**Comment by shaovoon** [comment]
Thanks for reporting the issue! I have reverted the commit.
